[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "xtask"
path = "Src/Main.rs"

[dependencies]
nih_plug_xtask = { path = "../../Library/nih-plug/nih_plug_xtask" }
anyhow = { workspace = true }

